- name: install repmgr
  sudo: true
  apt: pkg="{{item}}" state=present force=true update_cache=yes
  with_items:
    - repmgr=2.0~beta2-3
    - postgresql-9.3-repmgr=2.0~beta2-3
    - postgresql-contrib-9.3
